name: Build and Publish Frontend

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/meta-ad-studio-frontend:latest
            ghcr.io/${{ github.repository_owner }}/meta-ad-studio-frontend:${{ github.sha }}
name: Deploy Meta Ad Studio

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies for api-server
        run: cd src/backend/server && npm install --legacy-peer-deps

      - name: Run tests for api-server
        run: cd src/backend/server && npm test

      - name: Install dependencies for meta-verse-visualizer
        run: cd src/frontend/meta-verse-visualizer-main && npm install --legacy-peer-deps

      - name: Build meta-verse-visualizer
        run: cd src/frontend/meta-verse-visualizer-main && npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api-server image
        uses: docker/build-push-action@v4
        with:
          context: ./src/backend/server
          file: ./src/backend/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meta-ad-studio-api:latest

      - name: Build and push meta-verse-visualizer image
        uses: docker/build-push-action@v4
        with:
          context: ./src/frontend/meta-verse-visualizer-main
          file: ./src/frontend/meta-verse-visualizer-main/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meta-ad-studio-frontend:latest

      - name: Deploy to production
        run: echo "Deploying to production..."
