# This file will contain the values for the Velero Helm chart.
configuration:
  provider: aws
  backupStorageLocation:
    name: aws
    bucket: meta-studio-velero-backups
    config:
      region: us-east-1
  volumeSnapshotLocation:
    name: aws
    config:
      region: us-east-1

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.0
    volumeMounts:
      - mountPath: /target
        name: plugins

serviceAccount:
  server:
    create: true
