services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-devuser}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-meta_ad_studio}"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meta_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - meta_net

  api-server:
    build:
      context: ./src/backend/server
      dockerfile: Dockerfile
    image: meta_ad_studio_api:local
    env_file:
      - .env
    ports:
      - '3002:3001' # host:container
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://devuser:${POSTGRES_PASSWORD}@postgres:5432/meta_ad_studio}"
      REDIS_URL: "${REDIS_URL:-redis://redis:6379}"
    depends_on:
      - postgres
      - redis
    networks:
      - meta_net

  worker:
    build:
      context: ./src/backend/server
      dockerfile: Dockerfile
    image: meta_ad_studio_worker:local
    env_file:
      - .env
    command: npm run worker
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://devuser:${POSTGRES_PASSWORD}@postgres:5432/meta_ad_studio}"
      REDIS_URL: "${REDIS_URL:-redis://redis:6379}"
    networks:
      - meta_net

  meta-verse-visualizer-main:
    build:
      context: ./src/frontend/meta-verse-visualizer-main
      dockerfile: Dockerfile
    image: meta_ad_studio_visualizer:local
    ports:
      - '8082:80'
    depends_on:
      - api-server
    networks:
      - meta_net
    volumes:
      # Enable hot-reload during dev by mounting source (activate with 'profiles: ["dev"]')
      - ./src/frontend/meta-verse-visualizer-main:/app:cached

networks:
  meta_net:
    driver: bridge

volumes:
  postgres_data:

