version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command: '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   ports:
  #     - '9100:9100'
  #   networks:
  #     - app-network

  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   ports:
  #     - '3100:3100'
  #   volumes:
  #     - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
  #   command: '-config.file=/etc/loki/local-config.yaml'
  #   networks:
  #     - app-network

  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: '-config.file=/etc/promtail/config.yml'
  #   networks:
  #     - app-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge
