version: '3.8'

services:
  api-server:
    build:
      context: ./packages/api-server/server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - monitoring_net

  meta-verse-visualizer-main:
    build:
      context: ./packages/meta-verse-visualizer-main
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - api-server
    networks:
      - monitoring_net
    volumes:
      - ./packages/meta-verse-visualizer-main/src:/usr/src/app/src

networks:
  monitoring_net:
    driver: bridge

volumes:
  postgres_data:
