apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: meta-verse-visualizer-main
spec:
  selector:
    app: meta-verse-visualizer-main
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
