apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'api-server'
        static_configs:
          - targets: ['backend-service:3001']
  alert.rules.yml: |
    groups:
    - name: api-alerts
      rules:
      - alert: HighApiRequestLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job='api-server'}[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: page
        annotations:
          summary: High API request latency
          description: "The 95th percentile of API request latency is above 500ms for the last 5 minutes."

      - alert: HighApiErrorRate
        expr: sum(rate(http_requests_total{job='api-server', status=~'5..'}[5m])) / sum(rate(http_requests_total{job='api-server'}[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High API error rate
          description: "The API error rate is above 5% for the last 5 minutes."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.37.0
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      - name: prometheus-storage-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
