version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meta-studio-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meta-studio-database
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://meta-studio-user:password@db:5432/meta-studio-database"
      REDIS_URL: "redis://redis:6379"
    # Optional: Mount volumes for development to enable hot-reloading
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules

  frontend:
    build:
      context: ../..
  dockerfile: ./src/frontend/meta-verse-visualizer-main/Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
