groups:
- name: api-alerts
  rules:
  - alert: HighApiRequestLatency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job='api-server'}[5m])) by (le)) > 0.5
    for: 5m
    labels:
      severity: page
    annotations:
      summary: High API request latency
      description: "The 95th percentile of API request latency is above 500ms for the last 5 minutes."

  - alert: HighApiErrorRate
    expr: sum(rate(http_requests_total{job='api-server', status=~'5..'}[5m])) / sum(rate(http_requests_total{job='api-server'}[5m])) > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High API error rate
      description: "The API error rate is above 5% for the last 5 minutes."
