name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push image to Google Container Registry
        run: |-
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/meta-studio-flow
      
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy meta-studio-flow \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/meta-studio-flow \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
