# Vertex AI Pipeline for User Feedback Sentiment Analysis
# This pipeline trains and deploys a model to analyze user feedback and identify areas for improvement.

# 1. Dataset for training the sentiment analysis model
apiVersion: aiplatform.googleapis.com/v1
kind: Dataset
metadata:
  name: user-feedback-dataset
spec:
  displayName: User Feedback Logs
  metadataSchemaUri: gs://google-cloud-aiplatform/schema/dataset/metadata/text_1.0.0.yaml
  source:
    gcsSource:
      uris:
      - gs://your-project-feedback/user_feedback.log

---
# 2. Training pipeline for the sentiment analysis model
apiVersion: aiplatform.googleapis.com/v1
kind: TrainingPipeline
metadata:
  name: feedback-sentiment-analysis-training
spec:
  displayName: feedback-sentiment-analysis-training
  modelToUpload:
    displayName: feedback-sentiment-model
  inputDataConfig:
    datasetId: user-feedback-dataset
  trainingTaskDefinition: gs://google-cloud-aiplatform/schema/trainingjob/definition/automl_text_classification_1.0.0.yaml
  trainingTaskInputs:
    multiLabel: false
    targetColumn: sentiment # e.g., "positive", "negative", "neutral"

---
# 3. Endpoint for deploying the model
apiVersion: aiplatform.googleapis.com/v1
kind: Endpoint
metadata:
  name: feedback-sentiment-analysis-endpoint
spec:
  displayName: feedback-sentiment-analysis-endpoint

---
# 4. Deploy the model to the endpoint
apiVersion: aiplatform.googleapis.com/v1
kind: DeployedModel
metadata:
  name: feedback-sentiment-analysis-deployed-model
spec:
  endpoint: projects/your-project/locations/us-central1/endpoints/feedback-sentiment-analysis-endpoint
  model: projects/your-project/locations/us-central1/models/feedback-sentiment-model
  dedicatedResources:
    machineSpec:
      machineType: n1-standard-2
    minReplicaCount: 1
