name: Deploy Meta Ad Studio

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies for api-server
        run: cd packages/api-server/server && npm install --legacy-peer-deps

      - name: Run tests for api-server
        run: cd packages/api-server/server && npm test

      - name: Install dependencies for meta-verse-visualizer
        run: cd packages/meta-verse-visualizer-main && npm install --legacy-peer-deps

      - name: Build meta-verse-visualizer
        run: cd packages/meta-verse-visualizer-main && npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api-server image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/api-server/server
          file: ./packages/api-server/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meta-ad-studio-api:latest

      - name: Build and push meta-verse-visualizer image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/meta-verse-visualizer-main
          file: ./packages/meta-verse-visualizer-main/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meta-ad-studio-frontend:latest

      - name: Deploy to production
        run: echo "Deploying to production..."
