name: Release CI

on:
  push:
    # Trigger when a tag starting with 'v' is pushed, e.g. v1.0.0
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libnss3 libxtst-dev libgdk-pixbuf2.0-dev libfontconfig1-dev libxss-dev

      - name: Install project dependencies
        run: |
          npm ci

      - name: Build and package
        run: |
          # run the project packaging script (Electron builder / maker)
          npm run make

      - name: Publish Release and upload artifacts
        # This action will create a GitHub Release for the tag and upload files matched in 'files'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          files: |
            out/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
